const wordsArmenian = [
    { word: "գեղեցիկ" },
    { word: "շուն" },
    { word: "առաջ" },
    { word: "ամեն" },
    { word: "երկու" },
    { word: "այս" },
    { word: "անդադար" },
    { word: "գերազանց" },
    { word: "տեսնել" },
    { word: "գրել" },
    { word: "ուտել" },
    { word: "գործել" },
    { word: "գնալ" },
    { word: "արշավ" },
    { word: "աշխատել" },
    { word: "պատրաստել" },
    { word: "հաճախորդ" },
    { word: "կատարել" },
    { word: "առաջացնել" },
    { word: "անկում" },
    { word: "հասկանալ" },
    { word: "խնդրել" },
    { word: "գործարար" },
    { word: "հաճախորդ" },
    { word: "հարցնել" },
    { word: "հայերեն" },
    { word: "անգլերեն" },
    { word: "ռազմական" },
    { word: "համակարգչային" },
    { word: "մուտք" },
    { word: "ելք" },
    { word: "գրանցել" },
    { word: "մուտքագրել" },
    { word: "հիշել" },
    { word: "մուտքաբառ" },
    { word: "դիմել" },
    { word: "պատասխանել" },
    { word: "գրադարան" },
    { word: "պահել" },
    { word: "վերցնել" },
    { word: "արագ" },
    { word: "կարճ" },
    { word: "երկար" },
    { word: "բարձր" },
    { word: "նեղ" },
    { word: "հանգիստ" },
    { word: "առավոտ" },
    { word: "երեկո" },
    { word: "գիրք" },
    { word: "պատմություն" },
    { word: "մաթեմատիկա" },
    { word: "ֆիզիկա" },
    { word: "բժշկություն" },
    { word: "մուտքագրած" },
    { word: "վերացնել" },
    { word: "կուտակել" },
    { word: "ներկայացնել" },
    { word: "սովորել" },
    { word: "կարդալ" },
    { word: "վարկանիշ" },
    { word: "շաբաթ" },
    { word: "լուսաբաց" },
    { word: "ամբողջական" },
    { word: "ուրիշ" },
    { word: "միջազգային" },
    { word: "արտադրություն" },
    { word: "հարթակ" },
    { word: "հասցե" },
    { word: "կենդանի" },
    { word: "կաթ" },
    { word: "մատիտ" },
    { word: "կայծակ" },
    { word: "կարիճ" },
    { word: "լավ" },
    { word: "ավելի" },
    { word: "արձանագրել" },
    { word: "պահապանել" },
    { word: "վերացնել" },
    { word: "բույս" },
    { word: "գազ" },
    { word: "հոգեւորական" },
    { word: "առաջնորդել" },
    { word: "համեմատել" },
    { word: "մատուցել" },
    { word: "կաթնաղբյուր" },
    { word: "համեստ" },
    { word: "կոնֆերանս" },
    { word: "հատուկ" },
    { word: "առանձնացած" },
    { word: "հավաքել" },
    { word: "հատված" },
    { word: "ատամնաբույժ" },
    { word: "մեքենա" },
    { word: "հայր" },
    { word: "մայր" },
    { word: "որդի" },
    { word: "կենաց" },
    { word: "վառել" },
    { word: "գլխարկ" },
    { word: "ոտք" },
    { word: "ձեռնարկ" },
    { word: "տուն" },
    { word: "բոլորը" },
    { word: "մեր" },
    { word: "դուք" },
    { word: "նրանք" },
    { word: "ես" },
    { word: "դու" },
    { word: "մենք" },
    { word: "հարուստ"},
    { word: "վառարան" },
    { word: "խանութ" },
    { word: "խոհանոց" },
    { word: "սուրճ" },
    { word: "թակարդ" },
    { word: "թատրոն" },
    { word: "վարչապետ" },
    { word: "մրջյուն" },
    { word: "օպերա" },
    { word: "գայլ" },
    { word: "առյուծ" },
    { word: "բառախաղ" },
  ];

const wordsEnglish = [
    {"word": "hello"},
    {"word": "world"},
    {"word": "beautiful"},
    {"word": "awesome"},
    {"word": "fantastic"},
    {"word": "sunshine"},
    {"word": "butterfly"},
    {"word": "ocean"},
    {"word": "mountain"},
    {"word": "laughter"},
    {"word": "smile"},
    {"word": "garden"},
    {"word": "adventure"},
    {"word": "wonderful"},
    {"word": "delightful"},
    {"word": "serendipity"},
    {"word": "kindness"},
    {"word": "gratitude"},
    {"word": "harmony"},
    {"word": "treasure"},
    {"word": "brilliant"},
    {"word": "effervescent"},
    {"word": "whimsical"},
    {"word": "magnificent"},
    {"word": "tranquil"},
    {"word": "captivating"},
    {"word": "radiant"},
    {"word": "vibrant"},
    {"word": "inspiring"},
    {"word": "harmonious"},
    {"word": "splendid"},
    {"word": "majestic"},
    {"word": "fabulous"},
    {"word": "glorious"},
    {"word": "exquisite"},
    {"word": "enchanting"},
    {"word": "mesmerizing"},
    {"word": "blissful"},
    {"word": "ravishing"},
    {"word": "enlightening"},
    {"word": "breathtaking"},
    {"word": "phenomenal"},
    {"word": "stellar"},
    {"word": "charming"},
    {"word": "radiant"},
    {"word": "jubilant"},
    {"word": "enamored"},
    {"word": "mystical"},
    {"word": "ethereal"},
    {"word": "tranquility"},
    {"word": "majesty"},
    {"word": "graceful"},
    {"word": "serene"},
    {"word": "enchantment"},
    {"word": "splendor"},
    {"word": "resplendent"},
    {"word": "joyful"},
    {"word": "bewitching"},
    {"word": "celestial"},
    {"word": "idyllic"},
    {"word": "radiance"},
    {"word": "bliss"},
    {"word": "wondrous"},
    {"word": "luminous"},
    {"word": "serenity"},
    {"word": "captivation"},
    {"word": "tranquil"},
    {"word": "harmonize"},
    {"word": "euphoria"},
    {"word": "tranquility"},
    {"word": "ecstasy"},
    {"word": "halcyon"},
    {"word": "ambrosial"},
    {"word": "seraphic"},
    {"word": "gleaming"},
    {"word": "glow"},
    {"word": "cheerful"},
    {"word": "beaming"},
    {"word": "radiate"},
    {"word": "vivacious"},
    {"word": "blithe"},
    {"word": "peaceful"},
    {"word": "idyll"},
    {"word": "exultant"},
    {"word": "buoyant"},
    {"word": "contentment"},
    {"word": "jovial"},
    {"word": "exhilarating"},
    {"word": "buoyancy"},
    {"word": "beatific"},
    {"word": "triumphant"},
    {"word": "revitalize"},
    {"word": "festive"},
    {"word": "seraphic"},
    {"word": "gladden"},
    {"word": "felicitous"},
    {"word": "uplifting"},
    {"word": "radiant"},
    {"word": "paradise"},
    {"word": "joyous"},
    {"word": "mirth"},
    {"word": "blissful"},
    {"word": "radiant"}
];

const russianWords = [
  {"word": "привет"},
  {"word": "мир"},
  {"word": "красивый"},
  {"word": "потрясающий"},
  {"word": "фантастический"},
  {"word": "солнце"},
  {"word": "бабочка"},
  {"word": "океан"},
  {"word": "гора"},
  {"word": "смех"},
  {"word": "улыбка"},
  {"word": "сад"},
  {"word": "приключение"},
  {"word": "замечательный"},
  {"word": "восхитительный"},
  {"word": "судьбоносный"},
  {"word": "доброта"},
  {"word": "благодарность"},
  {"word": "гармония"},
  {"word": "сокровище"},
  {"word": "блестящий"},
  {"word": "игривый"},
  {"word": "великолепный"},
  {"word": "спокойный"},
  {"word": "завораживающий"},
  {"word": "лучезарный"},
  {"word": "яркий"},
  {"word": "вдохновляющий"},
  {"word": "гармоничный"},
  {"word": "великолепный"},
  {"word": "величественный"},
  {"word": "фабулозный"},
  {"word": "славный"},
  {"word": "изысканный"},
  {"word": "зачаровывающий"},
  {"word": "гипнотизирующий"},
  {"word": "блаженный"},
  {"word": "очаровательный"},
  {"word": "просветляющий"},
  {"word": "захватывающий"},
  {"word": "феноменальный"},
  {"word": "звездный"},
  {"word": "очаровательный"},
  {"word": "восторженный"},
  {"word": "очарованный"},
  {"word": "мистический"},
  {"word": "небесный"},
  {"word": "спокойствие"},
  {"word": "величие"},
  {"word": "изящный"},
  {"word": "спокойный"},
  {"word": "зачарование"},
  {"word": "великолепие"},
  {"word": "роскошный"},
  {"word": "радостный"},
  {"word": "завораживающий"},
  {"word": "небесный"},
  {"word": "идиллический"},
  {"word": "лучезарность"},
  {"word": "блаженство"},
  {"word": "чудесный"},
  {"word": "светящийся"},
  {"word": "спокойствие"},
  {"word": "захват"},
  {"word": "гармонизировать"},
  {"word": "эйфория"},
  {"word": "спокойствие"},
  {"word": "экстаз"},
  {"word": "спокойствие"},
  {"word": "нектар"},
  {"word": "серафический"},
  {"word": "сияющий"},
  {"word": "свет"},
  {"word": "веселый"},
  {"word": "светящийся"},
  {"word": "излучать"},
  {"word": "живой"},
  {"word": "беззаботный"},
  {"word": "мирный"},
  {"word": "идиллия"},
  {"word": "восторженный"},
  {"word": "поднимающий настроение"},
  {"word": "бодрящий"},
  {"word": "блаженство"},
  {"word": "радостный"},
  {"word": "веселье"},
  {"word": "лучезарный"},
  {"word": "радостный"},
];

